#!/usr/bin/env sh
# Usage: sue version
# Summary: Show Sue's Version
# Help: Shows Sue's version number.

set -e

SUE_PATH=$(which sue | sed 's/\libexec\/sue//g')
cd $SUE_PATH
VERSION=$(git describe --always --tags)

echo $VERSION
